In [ ]:
#Name: Shreetu Shrestha
#ID: 2417729

def convert_units(conversion_type, value):
    """
    Converts a value between different units of measurement.

    Parameters:
    conversion_type (str): The type of conversion to perform.
                           Options:
                           '1' - Meters to Feet
                           '2' - Feet to Meters
                           '3' - Kilograms to Pounds
                           '4' - Pounds to Kilograms
                           '5' - Liters to Gallons
                           '6' - Gallons to Liters
    value (float): The numeric value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == '1':
        return value * 3.28084
    elif conversion_type == '2':
        return value / 3.28084
    elif conversion_type == '3':
        return value * 2.20462
    elif conversion_type == '4':
        return value / 2.20462
    elif conversion_type == '5':
        return value * 0.264172
    elif conversion_type == '6':
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("Choose conversion type:")
    print("Length:")
    print("  1. Meters to Feet")
    print("  2. Feet to Meters")
    print("Weight:")
    print("  3. Kilograms to Pounds")
    print("  4. Pounds to Kilograms")
    print("Volume:")
    print("  5. Liters to Gallons")
    print("  6. Gallons to Liters")

    conversion_type = input("Enter your choice (1-6): ")

    try:
        value = float(input("Enter the value to convert: "))
        result = convert_units(conversion_type, value)

        if result is None:
            print("Error: Unsupported conversion type selected.")
        else:
            print(f"Converted value: {result:.4f}")

    except ValueError:
        print("Error: Please enter a valid numeric value.")

main();

Unit Conversion Program
Choose conversion type:
Length:
  1. Meters to Feet
  2. Feet to Meters
Weight:
  3. Kilograms to Pounds
  4. Pounds to Kilograms
Volume:
  5. Liters to Gallons
  6. Gallons to Liters
Enter your choice (1-6): 1
Enter the value to convert: 10
Converted value: 32.8084


In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum value.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum value.
    """
    return min(numbers)


def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        user_input = input("Enter numbers separated by spaces: ")
        numbers = list(map(float, user_input.split()))

        if len(numbers) == 0:
            raise ValueError("Empty list is not allowed.")

        if choice == '1':
            result = calculate_sum(numbers)
        elif choice == '2':
            result = calculate_average(numbers)
        elif choice == '3':
            result = find_maximum(numbers)
        elif choice == '4':
            result = find_minimum(numbers)
        else:
            print("Invalid operation selected.")
            return

        print("Result:", result)

    except ValueError:
        print("Error: Please enter valid numeric values and avoid empty input.")


if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 4
Enter numbers separated by spaces: 12 4 5 23
Result: 4.0


In [ ]:
def extract_every_other(lst):
  """
  Extracts every other element from a list.
  Parameters:
  lst: Input list
  Returns:
  list: A new list containing every other element
  """
  return lst[::2]


def get_sublist(lst, start, end):
  """
  Returns a sublist from start index to end index (inclusive)

  Parameters:
  lst: Input list
  start (int): Starting index
  end (int): Ending index

  Returns:
  list: The extracted sublist
  """
  return lst[start:end+1]


def reverse_list(lst):
  """
  Reverses a list using slicing

  Parameters:
  lst (list): Input list

  Returns:
  list: Reversed list
  """
  return lst[::-1]


def remove_first_last(lst):
  """
  Removes the first and last elements from a list.

  Parameters:
  lst (list): Input list.

  Returns:
  list: List without first and last elements.
  """
  return lst[1:-1]


def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
    lst (list): Input list.
    n (int): Number of elements to extract.

    Returns:
    list: First n elements.
    """
    return lst[:n]


def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
    lst (list): Input list.
    n (int): Number of elements to extract.

    Returns:
    list: Last n elements.
    """
    return lst[-n:]


def reverse_skip(lst):
    """
    Returns every second element starting from the second-to-last element,
    moving backward.

    Parameters:
    lst (list): Input list.

    Returns:
    list: Modified list as described.
    """
    return lst[-2::-2]


print(get_last_n([1, 2, 3, 4, 5, 6], 2))

[5, 6]


In [ ]:
def flatten(lst):
  """
  Returns a flattened list

  Parameters:
  lst (list): Input list

  Returns:
  list: Flattened list
  """
  flat_list = []
  for sublist in lst:
      for item in sublist:
          flat_list.append(item)
  return flat_list

def access_nested_element(lst, indices):
  """
  Accesses an element in nested list using a list of indices

  Parameters:
  lst (list): Nested list
  indices (list): List of indices

  Returns:
  element at the specidied position
  """

  element = lst
  for index in indices:
    element = element[index]
  return element

def sum_nested(lst):
  """
  Cakcukated the sum of all elements in a nested list

  Parameters:
  lst (list): Nested list

  Returns:
  int/float: total sum of all elements
  """

  total = 0
  for item in lst:
    if isinstance(item,list):
      total += sum_nested(item)
    else:
      total += item
  return total

def remove_element(lst, elem):
  """
  Removes all occurances of element from a nested list

  Parameters:
  lst (list): Nested list
  elem: element ot remove

  Returns:
  list: modified list without element
  """

  new_list = []
  for item in lst:
    if isinstance(item, list):
      new_list.append(remove_element(item, elem))
    elif item != elem:
      new_list.append(item)
  return new_list

def find_max(lst):
  """
  Finds maximum element in a nested list

  Parameters:
  lst(list): Nested list

  Returns:
  int/float: Maximun element
  """
  max_value= None

  for item in lst:
    if isinstance(item, list):
      value = find_max(item)
    else:
      value = item

    if max_value is None or value > max_value:
      max_value = value
  return max_value

def count_occurrences(lst, elem):
  """
  counts occurences of elements in list

  Parameters:
  lst (list): Input list
  elem: element to count

  Returns:
  int: number of occurences
  """
  count = 0
  for item in lst:
    if isinstance(item,list):
      count += count_occurrences(item, elem)
    elif item == elem:
      count += 1
  return count

def deep_flatten(lst):
  """
  Flattens a deeply nested list into a single list.

  Parameters:
  lst (list): Deeply nested list.

  Returns:
  list: Fully flattened list.
  """
  flat_list = []
  for item in lst:
      if isinstance(item,list):
          flat_list.extend(deep_flatten(item))
      else:
          flat_list.append(item)
  return flat_list

def average_nested(lst):
  """
  calculated the average of all elements in a nested list
  parameters:
  lst(list): nested list

  Returns:
  float: Average value
  """
  flat = deep_flatten(lst)
  return sum(flat)/ len(flat)

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(flatten([[1, 2], [3, 4], [5]]))
print(access_nested_element(lst, [1, 2]))
print(sum_nested([[1, 2], [3, [4, 5]], 6]))
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))
print(find_max([[1, 2], [3, [4, 5]], 6]))
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(average_nested([[1, 2], [3, 4], [5, 6]]))


[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


NumPy

In [2]:
import numpy as np
zero_arr = np.zeros((2,3))
print("zero array \n",zero_arr, " with dimension: ",zero_arr.shape)

zero_dim = np.array(5)
one_dim = np.array([1,2])
n_dim = np.array([[1,2],[1,2]])

for arr in [zero_dim, one_dim, n_dim]:
  print(f"Array:{arr}\n Dimension: {arr.ndim}\nData type: {arr.dtype}\n")

zero array 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimension:  (2, 3)
Array:5
 Dimension: 0
Data type: int64

Array:[1 2]
 Dimension: 1
Data type: int64

Array:[[1 2]
 [1 2]]
 Dimension: 2
Data type: int64



In [10]:
#Problem - 1: Array Creation:

empty_arr = np.empty((2,2))
print("empty array: ",empty_arr)

ones_arr = np.ones((2,2))
print("\nones array: ",ones_arr)

arr1 = np.full((3,3), 8, dtype= int)
print("\nfull array: \n",arr1)

arr2 = np.zeros_like(arr1)
print("\narrays of zeros as given array \n",arr2)

arr3 = np.ones_like(arr1)
print("\narrays of zeros as given array \n",arr3)

new_list = [1,2,3,4,5]
arr4 = np.array(new_list)
print("\narray from list: ",arr4)



empty array:  [[1. 1.]
 [1. 1.]]

ones array:  [[1. 1.]
 [1. 1.]]

full array: 
 [[8 8 8]
 [8 8 8]
 [8 8 8]]

arrays of zeros as given array 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

arrays of zeros as given array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

array from list:  [1 2 3 4 5]


In [11]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
arr1 = np.arange(10,49)
print(arr1)

arr2 = np.arange(9).reshape(3,3)
print(arr2)

identity_matrix = np.eye(3)
print(identity_matrix)

rand_arr = np.random.random(30)
print("Mean:", rand_arr.mean())

rand_10 = np.random.random((10, 10))
print("Minimum:", rand_10.min())
print("Maximum:", rand_10.max())

zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)

checker = np.zeros((8,8))
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print(checker)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 0.591314464629384
Minimum: 6.456988186553936e-05
Maximum: 0.9999894451215945
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [14]:
#Problem - 3: Array Operations:x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(x-y)
print(x*y)
print(x**2)

print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =\n", np.dot(x, y))

print(np.vstack((x, y)))
print(np.vstack((v, w)).T)

# np.concatenate((x, v))



[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


x and v cannot concatenate because they have different dimensions

In [23]:
#Problem - 4: Matrix Operations:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

print("AB =\n", np.dot(A, B))
print("BA =\n", np.dot(B, A))

AB = np.dot(A, B)
left = AB.T
right = np.dot(B.T, A.T)

print("Left:\n", left)
print("Right:\n", right)

A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution [x, y, z]:\n", X)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Left:
 [[23 51]
 [13 29]]
Right:
 [[23 51]
 [13 29]]
Solution [x, y, z]:
 [ 2.  1. -2.]


In [25]:
#Experiment: How Fast is Numpy?

import time
import numpy as np
import random

size = 1_000_000

list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python List Addition Time:", end - start)

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_numpy = arr1 + arr2
end = time.time()
print("NumPy Addition Time:", end - start)

start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python List Multiplication Time:", end - start)

start = time.time()
result_numpy = arr1 * arr2
end = time.time()
print("NumPy Multiplication Time:", end - start)

start = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python Dot Product Time:", end - start)

start = time.time()
dot_numpy = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start)

n = 300
matrix1 = [[random.random() for _ in range(n)] for _ in range(n)]
matrix2 = [[random.random() for _ in range(n)] for _ in range(n)]

start = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(n))
                  for j in range(n)] for i in range(n)]
end = time.time()
print("Python Matrix Multiplication Time:", end - start)


A = np.array(matrix1)
B = np.array(matrix2)

start = time.time()
result_numpy_matrix = np.dot(A, B)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)

Python List Addition Time: 0.14289283752441406
NumPy Addition Time: 0.004380226135253906
Python List Multiplication Time: 0.1277470588684082
NumPy Multiplication Time: 0.0026082992553710938
Python Dot Product Time: 0.09081745147705078
NumPy Dot Product Time: 0.001638650894165039
Python Matrix Multiplication Time: 5.3233325481414795
NumPy Matrix Multiplication Time: 0.0028734207153320312
